### ISSUE TITLE
Rails Encrypted Credentials

### ISSUE THREAD

**Issue by paulfioravanti** [rubyaustralia/roro#154]
From `secrets.yml` to Encrypted Secrets, and now to Encrypted Credentials, Rails has gone through a few solutions to get this functionality right. This is a request for an introductory presentation on Encrypted Credentials in Rails 5.2

**Comment by leesheppard** [comment]
@cheddachedda @Yasmin-A95 Happy to do this talk when there's space available in the schedule.

**Comment by Yasmin-A95** [comment]
Hey @leesheppard, we'd love to have you give this for our[ October 10 meetup](https://github.com/rubyaustralia/roro/issues/154) if you're available for it :)

**Comment by cheddachedda** [comment]
Thanks for that great talk Lee!
