### ISSUE TITLE
Integrating a front end technology with Webpacker

### ISSUE THREAD

**Issue by paulfioravanti** [rubyaustralia/roro#156]
Rails 5.1 introduced the `--webpack` option to make it easier to integrate React/Angular/Vue/Elm/etc into a Rails app.  This is a request for a presentation showing how you used Webpacker in a Rails app, using any front end technology of your choosing.

**Comment by catherine-jones** [comment]
👍

**Comment by christopheragnus** [comment]
I would love if someone did this!

**Comment by paulfioravanti** [comment]
Marking as stale. If anyone wants to pick it up in the future, feel free to re-open.
