### ISSUE TITLE
Introduction to Fie, a front-end framework for Rails

### ISSUE THREAD

**Issue by paulfioravanti** [rubyaustralia/roro#177]
This is a presentation request for someone to do an Introduction to [Fie](https://fie.eranpeer.co/). Fie is a framework for Ruby on Rails that shares the state of your views with the backend. "Hello World" tutorial [here](https://fie.eranpeer.co/start).

If anyone ever does the #153 presentation, this might be an interesting comparative example, _or_ a tutorial on this could be rolled into #153 to be a bigger talk about the current state of Rails-specific front-end frameworks.

**Comment by leesheppard** [comment]
Fie seems to have been abandoned for some years now. The official site is not working either. 

[fie.eranpeer.co](https://fie.eranpeer.co/)

[Fie on GH](https://github.com/raen79/fie)
