### ISSUE TITLE
Integrating react.js with Rails

### ISSUE THREAD

**Issue by konami99** [rubyaustralia/roro#261]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)

Richard Chou

- Brief summary of the talk content

How to integrate react and redux into existing rails app; plus some useful tips on writing react.

- Which month's meetup you would like to present at

March 2020

- Length of talk (please try to keep to ~15 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)

15 minutes

- Your Twitter username (if you have one)

None

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

![Screen Shot 2020-03-06 at 3 05 17 pm](https://user-images.githubusercontent.com/166879/76050570-ef81b680-5fbb-11ea-977b-438cd7f47aa4.png)

**Comment by mathewdbutton** [comment]
Hi @konami99, thank you for submitting an issue, unfortunately we've lined up too many speakers for this months RORO meetup so we need to move your talk to April's Meetup. we're still keen to have you present, our intention is to keep the audience fresh for it. I'll see you on Tuesday.

**Comment by mathewdbutton** [comment]
Hey @konami99 
I hope the self isolation is treating you well, we're looking to try and do the next RORO virtually, and we wanted to know if you'd be interested in joining in on this experimental ROROSyd?
