### ISSUE TITLE
jsbundling, cssbundling and propshaft

### ISSUE THREAD

**Issue by langsharpe** [rubyaustralia/roro#312]
Last month we migrated from webpacker to a combination of jsbundling-rails, cssbundling-rails, propshaft, esbuild, postcss, sass and tailwind. What is this long list of project names, why is it better and how should you get there.

Which month's meetup you would like to present at: End of June
Length of talk: 10-15 minutes
Your Twitter username: @langsharpe
Are you happy to have your talk published on the RubyAU YouTube channel?: Yes
Link to, or upload of, a photo of yourself: https://pbs.twimg.com/profile_images/1513745382240821248/-hzEroVi_400x400.jpg

**Comment by mathewdbutton** [comment]
YAHOO! Thanks @langsharpe that's wicked.

You are locked in for June 28th!
