### ISSUE TITLE
Jr Dev on Growing Pains and Becoming a Huge Nerd

### ISSUE THREAD

**Issue by Yasmin-A95** [rubyaustralia/roro#313]
### Was this a terrible terrible mistake?

A dive into whether or not quitting my job and enrolling in a Software Engineering Bootcamp was the best thing I've ever done for myself or a terrible mistake. A light-hearted and hopefully funny talk about going from no coding experience to sort of kind of having some idea of what the hell I'm doing. Maybe. I'd like to throw in bits about the sort of code that I've discovered I love - and the general journey from me being jaded and just wanting to become a programmer because I knew it made decent money, to now seeing code as a form of creative expression that I'm really passionate about.

- Which month's meetup you would like to present at
October 11
- Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!)
5-10 minutes
- Your Twitter username (if you have one)
@Yasmin_Arch
- Are you happy to have your talk published on the RubyAU YouTube channel?
Yep! 

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
me and my cat
<img width="554" alt="MeandBoo" src="https://user-images.githubusercontent.com/107013100/192436815-4b46497d-b84d-4baa-8352-5e53e60d7e42.PNG"> 

an alternative if my catto isn't appropriate 
<img width="478" alt="Me and Art pic" src="https://user-images.githubusercontent.com/107013100/192436824-efc480c2-734c-4a4a-94e9-7bb92fa54360.png"> 

General Assembly took some proffesh shots of us so I may update this before the event but I'll let you know!

**Comment by mathewdbutton** [comment]
YEEEEHAAAA! You're scheduled in for October @Yasmin-A95! thank you very much!

**Comment by mathewdbutton** [comment]
Thanks for updating the info, perfect. Ohhh nice, proffesh shots are always nice, for comparison, I use the ridiculous profile photo of me in a pickle costume for most of mine, so feel free to go either way :)

**Comment by mathewdbutton** [comment]
Thanks for updating the info, perfect. Ohhh nice, proffesh shots are always nice, for comparison, I use the ridiculous profile photo of me in a pickle costume for most of mine, so feel free to go either way :).

Also I was just wondering, how do you pronounce your name?

**Comment by Yasmin-A95** [comment]
Tbf my cat photo is a strong preference and I'd use it on linkedin if I
could get away with it 😅

**Comment by mathewdbutton** [comment]
I finally got around to uploading your recording to youtube WOOH! 
https://youtu.be/K6RJzkKTqNg

Thanks again for speaking!
