### ISSUE TITLE
Awesome GitHub Landing Page

### ISSUE THREAD

**Issue by friendlyantz** [rubyaustralia/roro#316]
Proposing a lightning talk for RORO ~~Sydney!~~ Melbourne!

- Titile(WIP): Awesome GitHub Profile / Landing Page
- About: how to make your main gitHub profile page look fantastic 🚂 , and perhaps touch on elementary bits of TDD and static website framework used on GitHub(Jekyll) 
- Timing: Nov-2022
- Are you happy to have your talk published on the RubyAU YouTube channel? -> `yes`
- Your Twitter username (if you have one) -> [@friendlyantz](https://twitter.com/friendlyantz)
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: 
![image](https://user-images.githubusercontent.com/70934030/199131724-7f0f0a0f-0a42-4e96-9df7-0f763c3ff2b9.png)

**Comment by mathewdbutton** [comment]
Hey Anton, thanks for creating an issue. If this is for Melbourne, then I'd recommend creating an issue on the Melbourne RORO github repo :)
https://github.com/rubyaustralia/melbourne-ruby

**Comment by friendlyantz** [comment]
Thanks, was just asking Kevin about it, couldn't find melbs repo. will move it there, cheers

**Comment by friendlyantz** [comment]
moved here [https://github.com/rubyaustralia/melbourne-ruby/issues/192](https://github.com/rubyaustralia/melbourne-ruby/issues/192)
