### ISSUE TITLE
Exercism: Protein Translation 

### ISSUE THREAD

**Issue by Manderson3568** [rubyaustralia/roro#317]
Thanks for volunteering for to showcase the Exercism challenge at RORO Sydney!

Please provide the following information:

- Name of challenge Protein Translation 
- Which month's meetup you would like to present at November
- Are you happy to have your talk published on the RubyAU YouTube channel? Ask me that question again after we see how much of a nervous wreck I am in the presentation
- Your Twitter username (if you have one) @michaelanderdev
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts) https://drive.google.com/file/d/1u1tnv9jDvVT2NZ9ebQ1LHuN2AaqnWLyb/view?usp=sharing

**Comment by Yasmin-A95** [comment]
Thanks for volunteering for to do the exercism challenge for the coming meetup (14th of November)! If you need any help or further info, don't hesitate to reach out either by submitting an issue or just DM me. Very glad to have you as a speaker!

**Comment by mathewdbutton** [comment]
Hey @Manderson3568, just double checking you're still okay to present next Tuesday (Nov 15th)?

If as Yasmin mentioned, if we can help with anything or if you've got any questions, drop us a line.

**Comment by Yasmin-A95** [comment]
Thank you so much for taking on the exercism challenge. Everyone was so impressed with your recursive solution!

If you want to throw it in a codepen or something like that and tweet it @rorosyd we can give it a retweet 😁
