### ISSUE TITLE
Hotwire: Lessons learned deploying Turbo & Stimulus in a production app at scale…..

### ISSUE THREAD

**Issue by tarun-delish** [rubyaustralia/roro#318]
- Content summary: _Transitioning from a Javascript/jQuery SPA mindset to a Turbo/Stimulus-directed approach is not as simple as DHH would lead you to believe; Implementing Hotwire in a production application at scale is no childs-play & can be fraught with uncertainties; I will share some tips on how to avoid trouble and debugging tricks when you do inevitably yourself lost..._   
- _November 15 Sydney_ RORO
- _App Length of talk will be_ 20 mins
- I'm not active on twitter(gasp!) but you can find me on linked in and RubyAU Slack
- _Are you happy to have your talk published on the RubyAU YouTube channel?_ Yes
- _Link to, or upload of, a photo of yourself that will appear in the meetup slide deck_ [link](https://images.app.goo.gl/8cYK8pkVEW2RCDS97)

**Comment by Yasmin-A95** [comment]
Thank you for volunteering to speak at the 15th of Nov meetup. This sounds like a great one! If you need help with anything further info don't hesitate to reach out either by submitting an issue or DMing me / the other organisers. Super glad to have you!

**Comment by Yasmin-A95** [comment]
Thanks for giving your talk @tarun-delish
I'm keen for part two! 

When you get the chance, could you please export your slides to PDF and put them on a slide-sharing platform (Slideshare, SpeakerDeck, etc), then tweet the link to @rorosyd so we can retweet it?
