### ISSUE TITLE
How to develop your rails application on GitHub codespaces

### ISSUE THREAD

**Issue by the-dina** [rubyaustralia/roro#321]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk: Develop your rails application on GitHub codespaces
- Brief summary of the talk content: It will be a brief talk about docker containers and how to set up your devcontainer to develop your rails/mysql application on GitHub codespaces 
- Which month's meetup you would like to present at: Feb 2023
- Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!): 25 min will work 🤞 
- Your Twitter username: Not a fan of Elon Musk 😄 
- Are you happy to have your talk published on the RubyAU YouTube channel? Sure, My pleasure.
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: The github one works: https://avatars.githubusercontent.com/u/120369808?s=400&u=021d068ff9c292f3e1d2a6d187510d4ca16f82b6&v=4

**Comment by mathewdbutton** [comment]
WOW! Thanks @the-dina this sounds amazing, you're locked in for our Feb 14th Meetup!

**Comment by the-dina** [comment]
Thanks heaps @mathewdbutton! And see you 14th of Feb then.

I will bring my personal laptop, which has an HDMI input. Is there anything else I need to bring?

**Comment by mathewdbutton** [comment]
That works perfect, Cool the projector has HDMI so we're all covered there. You should need to bring anything else (maybe power, if it's a mac we normally have our own chargers there)

**Comment by cheddachedda** [comment]
Hey @the-dina just confirming you're still good to go for next Tuesday night?

**Comment by the-dina** [comment]
> Hey @the-dina just confirming you're still good to go for next Tuesday night?
> 
> * Dan from Rorosyd

Hey @cheddachedda, thanks and yes. See you on Tuesday!

**Comment by cheddachedda** [comment]
Amazing! Looking forward to it!

**Comment by the-dina** [comment]
Me too! thanks Dan!

**Comment by Yasmin-A95** [comment]
Thank you for speaking! Your talk was amazing, I have a couple people who would be very keen on watching the youtube video you recorded. We usually ask speakers to export their slides to pdf and upload them to a slide sharing platform of their choice (Slideshare, Speakerdeck, or wherever else suits) and tweet them @rorosyd. Twitter is a bit of a mess right now though so it's up to you :)

**Comment by the-dina** [comment]
Hi @Yasmin-A95 , thanks for having and Kudos to rorosyd team for gathering the community and making good things happen

I don't have a Twitter account, but I uploaded the slides on Slideshare and this is the link: https://www.slideshare.net/DinaEsmaeili/introduction-to-codespaces
And this is the recorded video: https://www.youtube.com/watch?v=G_hKdCcwH_Q

Have a nice one.

**Comment by Yasmin-A95** [comment]
Thanks! @the-dina
