### ISSUE TITLE
Why you should use AASM (If you aren't already)

### ISSUE THREAD

**Issue by tobyturnbull** [rubyaustralia/roro#322]
Thanks for proposing a talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content -- Covering the AASM gem and why state machines are important.
- Which month's meetup you would like to present at --  Feb 2023 (SYD)
- Length of talk (please try to keep to ~15 - 25 minutes, but we're happy to allow wiggle room; however, the more succinct, the better!) -- ~15-20
- Your Twitter username (if you have one) -- N/A
- Are you happy to have your talk published on the RubyAU YouTube channel?
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts) -- Getting headshots Friday! Will load here once done

**Comment by mathewdbutton** [comment]
Hell yeah, thanks @tobyturnbull, this looks great, you're locked in for our Feb 14th Meetup!

**Comment by cheddachedda** [comment]
Hey @tobyturnbull just confirming you're still good to go for next Tuesday night?

**Comment by Yasmin-A95** [comment]
Thanks for speaking this week! 

We usually ask people to export their slides to pdf and upload them to a slide sharing platform of their choice (speakerdeck, slideshare, etc) and tweet @rorosyd—but twitter's going down and you don't have one anyway 🤷‍♀️ Though if you're keen I can tweet it out for you and link to your github or wherever else you'd prefer people to follow you.
