### ISSUE TITLE
Faster Rails

### ISSUE THREAD

**Issue by Coreastreet** [rubyaustralia/roro#323]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- Name of talk (in the title field): Faster Rails (focus on database)
- Brief summary of the talk content: This content will focus on two subtopics: Performance monitoring and most common ways to improve response times. (N+1 queries and database indicies, if enough, maybe also caching and memory allocation too)          
- Which month's meetup you would like to present at: February (This month)
- Are you happy to have your talk published on the RubyAU YouTube channel? Yes
- Your Twitter username (if you have one) 
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts):
             https://www.dropbox.com/s/kdxlbxuguw8azjd/default_1.1.3.png?dl=0

**Comment by cheddachedda** [comment]
👋 Hey @Coreastreet it's Dan from Rorosyd. We're all good for speakers for this Tuesday's meetup, but it'd be great to have you for next month if you're available (Mar 14). We always want to hear about faster Rails

**Comment by Coreastreet** [comment]
Sure, no problem.

**Comment by cheddachedda** [comment]
Awesome. We'll follow up closer to the date

**Comment by Yasmin-A95** [comment]
Hey @Coreastreet, are you still up for giving this talk for the March 14 meetup?

**Comment by Coreastreet** [comment]
Hi Yasmin,

Yes, I am still interested in giving a talk.

Regards,
Justin

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Yasmin-A95** [comment]
Amazing! Thank you, we're really excited to have you. If you have any questions (or requests etc) feel free to reach out to me or any of the other organizers. See you on the 14th.

**Comment by cheddachedda** [comment]
Hey Justin, I'm just about to update the Meetup event page with our speaker info.

- Did you want to edit your summary of your talk? Otherwise I'll just take what you've written above. You can add caching and memory allocation to your talk if you'd like.
- Do you have a full name that we can post with it, or even company/role (optional)?
- Do you know how long your talk will go?

Also, are you on our Ruby Australia slack channel?

**Comment by Coreastreet** [comment]
Hey Daniel, thanks for reaching out.

To answer your questions -

1. I am happy for you to post my summary as it is.

I don't plan on adding caching and memory allocation in talk.

2. Justin Ye, ruby enthusiast and current working at the NSW electoral commission in the contact center team.

3. It is a lightning talk, so should last around 5mins.

4. Yes, I have joined the Ruby Australia slack channel.

Regards,

Justin

________________________________

**Comment by Yasmin-A95** [comment]
Hi Justin, thank you again for your talk. It has been uploaded to the Ruby Australia YouTube channel, check it out [here](https://www.youtube.com/watch?v=HLwEgSzK7So). If you'd like to choose a thumbnail feel free to send one over, perhaps if you still have the slides we could use one of those?

**Comment by Coreastreet** [comment]
Hi Yasmin,

Here is a link to the powerpoint presentation that anyone can use to access it.
[https://res.cdn.office.net/assets/mail/file-icon/png/pptx_16x16.png]Presentation 3.pptx<https://1drv.ms/p/s!Ag5EVY-l6q_3i1UJKaYUWx_1Nqgp?e=qJu6hC>
Thanks for the chance to present.

Regards,
Justin
________________________________
