### ISSUE TITLE
Exercism: [Bob]

### ISSUE THREAD

**Issue by aquillo-au** [rubyaustralia/roro#324]
Thanks for volunteering for to showcase the Exercism challenge at RORO Sydney!

Please provide the following information:

- Name of challenge Bob
- Which month's meetup you would like to present at - March
- Are you happy to have your talk published on the RubyAU YouTube channel? Yes
- Your Twitter username (if you have one) NA
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
![Ben-Greig-e1665553481805](https://user-images.githubusercontent.com/40282417/218888263-80169c43-2d42-468e-80b2-da6597ec6385.jpg)

**Comment by Yasmin-A95** [comment]
Thanks for offering to take on our exercism challenge @aquillo-au , we're thrilled to have you! You're locked in for Tuesday March 14th. If you have any questions feel free to contact me or any of the other organizers.
