### ISSUE TITLE
Turbo Stream

### ISSUE THREAD

**Issue by aquillo-au** [rubyaustralia/roro#325]
Thanks for proposing a lightning talk for RORO Sydney!

Please provide the following information:

- Brief summary of the talk content
A snappy talk about the power of Turbo stream in rails 7, (could show how to use it with a react frontend if that was preferred)
- Which month's meetup you would like to present at -Could do march or April

- Are you happy to have your talk published on the RubyAU YouTube channel? Yes
- Your Twitter username (if you have one)
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

Just to note I'm fairly early on my ruby journey, but i figured given Hotwire's turbo stream is new to rails 7 and rails is generally not used for front end stuff there may be some things people haven't played with yet.

**Comment by Yasmin-A95** [comment]
@aquillo-au Two talks! You're a gem. Which one would you like to present for the March meetup?

**Comment by aquillo-au** [comment]
I don't mind too much which of the two I end up doing, I guess its whichever is most useful for the meetup,

**Comment by aquillo-au** [comment]
Love to, Will see you in March with all about bob :)
